<?php


namespace Nadmin\WcmBundle\Helper;


use Nadmin\WcmBundle\Entity\Document;
use Symfony\Component\Form\Form;

use Symfony\Component\HttpFoundation\File\Exception\FileException;
use Symfony\Component\HttpFoundation\File\UploadedFile;

Trait ControllerTrait
{


    public function saveImage($image)
    {
        if ($image) {
            $path = '../upload/images/';


            $filename = $this->generateUniqueFileName() . '.' . $image->guessExtension();
            $document = new Document();

            /**
             * @var $img \Symfony\Component\HttpFoundation\File\UploadedFile
             */
            $document
                ->setOriginalFilename($image->getClientOriginalName())
                ->setAssetFilename($filename)
                ->setMimeType($image->getMimeType())
                ->setPath($path)
                ->setSize($image->getSize());

            $image->move(
                $path,
                $filename
            );

            $this->getEm()->persist($document);
            $this->getEm()->flush();

            return $document;
        }

        return false;
    }

    public function uploadFile(UploadedFile $file)
    {
        $originalFilename = pathinfo($file->getClientOriginalName(), PATHINFO_FILENAME);
        $safeFilename = transliterator_transliterate('Any-Latin; Latin-ASCII; [^A-Za-z0-9_] remove; Lower()', $originalFilename);
        $fileName = $safeFilename . '-' . uniqid() . '.' . $file->getClientOriginalExtension();

        try
        {
            $file->move($this->getParameter('images_directory'), $fileName);
        }
        catch (FileException $e)
        {

        }

        return $fileName;
    }

    public function getTargetDirectory()
    {
        return $this->targetDirectory;
    }


    public function uploadFiles($fileCollection)
    {
        foreach ($fileCollection as $file)
        {
            $this->uploadFile($file);
        }
    }

    public function save($entity)
    {
        $this->getEm()->persist($entity);
        $this->getEm()->flush();
    }

    public function remove($entity)
    {
        $this->getEm()->remove($entity);
        $this->getEm()->flush();
    }

    public function removeEmptyImages(Chien $chien)
    {
        foreach ($chien->getImages() as $image)
        {
            if ($image->getFile() == null)
            {
                $chien->removeImage($image);
            }
        }
    }


    public function getEm()
    {
        return $this->getDoctrine()->getManager();
    }

    public function isValid(Form &$form, $request)
    {
        $form->handleRequest($request);

        return   $form->isSubmitted() && $form->isValid();
    }

    /**
     * @return string
     */
    public function generateUniqueFileName()
    {
        // md5() reduces the similarity of the file names generated by
        // uniqid(), which is based on timestamps
        return md5(uniqid());
    }
}
